In [11]:
import pandas as pd
from absl.testing.parameterized import named_parameters

# Load data from CSV file
df = pd.read_csv("bonus.csv")
df.head()

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    1                   3    116
1     EMP_002            4                    8                  10    136
2     EMP_003            8                    4                   5    150
3     EMP_004            5                    4                   7    118
4     EMP_005            7                    5                   6    146

In [12]:
df.shape

(1000, 5)

In [13]:
from sklearn.model_selection import train_test_split

X = df[['performance', 'years_of_experience', 'projects_completed']].values
y = df[['bonus']].values  # Ensure target is a 2D array for

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [14]:
X_train.shape

(800, 3)

In [15]:
X_test.shape

(200, 3)

In [16]:
import torch
import torch.nn as nn
import torch.optim as optim

In [17]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [18]:
class BonusPredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(3, 1),  # 3 input features -> 1 output neuron
        )
    def forward(self, x):
        return self.network(x)

In [24]:
model = BonusPredictor()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.005)

In [25]:
epochs = 5000

for epoch in range(epochs):
    # Forward pass
    predictions = model(X_train_tensor)
    loss = criterion(predictions, y_train_tensor)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()

    # Update weights
    optimizer.step()

    # Print loss every 100 epochs
    if (epoch+1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.2f}')

Epoch [100/5000], Loss: 20.57
Epoch [200/5000], Loss: 17.99
Epoch [300/5000], Loss: 15.79
Epoch [400/5000], Loss: 13.89
Epoch [500/5000], Loss: 12.22
Epoch [600/5000], Loss: 10.76
Epoch [700/5000], Loss: 9.47
Epoch [800/5000], Loss: 8.34
Epoch [900/5000], Loss: 7.34
Epoch [1000/5000], Loss: 6.46
Epoch [1100/5000], Loss: 5.69
Epoch [1200/5000], Loss: 5.01
Epoch [1300/5000], Loss: 4.41
Epoch [1400/5000], Loss: 3.88
Epoch [1500/5000], Loss: 3.42
Epoch [1600/5000], Loss: 3.01
Epoch [1700/5000], Loss: 2.65
Epoch [1800/5000], Loss: 2.33
Epoch [1900/5000], Loss: 2.06
Epoch [2000/5000], Loss: 1.81
Epoch [2100/5000], Loss: 1.59
Epoch [2200/5000], Loss: 1.40
Epoch [2300/5000], Loss: 1.24
Epoch [2400/5000], Loss: 1.09
Epoch [2500/5000], Loss: 0.96
Epoch [2600/5000], Loss: 0.84
Epoch [2700/5000], Loss: 0.74
Epoch [2800/5000], Loss: 0.65
Epoch [2900/5000], Loss: 0.58
Epoch [3000/5000], Loss: 0.51
Epoch [3100/5000], Loss: 0.45
Epoch [3200/5000], Loss: 0.39
Epoch [3300/5000], Loss: 0.35
Epoch [3400/5

In [26]:
model.eval()

with torch.no_grad():
    test_predictions = model(X_test_tensor)
    test_loss = criterion(test_predictions, y_test_tensor)
    print(f'Test Loss: {test_loss.item():.2f}')

Test Loss: 0.04


In [28]:
X_test_tensor[:3]

tensor([[ 8.,  9., 10.],
        [ 9.,  2.,  5.],
        [ 3.,  7.,  8.]])

In [29]:
test_predictions[:3]

tensor([[189.9589],
        [150.1525],
        [113.7365]])

In [30]:
y_test_tensor[:3]

tensor([[190.],
        [150.],
        [114.]])

In [34]:
for name, value in model.named_parameters():
    print(f"Name: {name} | Values : {value[:2]}")

Name: network.0.weight | Values : tensor([[12.0327,  5.8459,  2.1836]], grad_fn=<SliceBackward0>)
Name: network.0.bias | Values : tensor([19.2486], grad_fn=<SliceBackward0>)
